name: Update Profile Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Activity Graph
      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: jagennath-hari
          options: theme=react-dark&area=true&hide_border=true&bg_color=20232a
          output_path: dist/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # GitHub Trophies
      - name: Generate GitHub trophies
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: 'username=jagennath-hari&theme=darkhub&title=-Issues,-Reviews&column=7&no-frame=true&no-bg=true&margin-w=8'
          path: dist/trophies.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Publish both
      - name: Publish profile SVGs
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
